### ISSUE TITLE
Problem: nonce increment logic cause deliver_tx fail

### ISSUE THREAD

**Issue by yihuang** [crypto-com/thaler-docs#112]
For example, 
- In check_tx, tx nonce match staking state, tx passed.
- In begin block, nonce of staking state increased because of cleanup or punishment.
- In deliver_tx, tx nonce check failed.

Another issue, from the perspective of client:
- begin block, nonce increased(uncommitted)
- query nonce, get the old(last committed) nonce.
- send tx, execution failed.

In integration tests, it happens quite frequently, public tx execution failed because of nonce mismatch.
It seems mostly caused by cleanup operation increase nonce, maybe we can remove the nonce increasing from cleanup operation.

**Comment by tomtau** [comment]
In the real setting, this should be fairly rare, as begin block updates should be less frequent

**Comment by yihuang** [comment]
> In the real setting, this should be fairly rare, as begin block updates should be less frequent

But it already causes the unstable of integration tests, it got worse in recent revisions because now abci-query read committed staking state.

**Comment by tomtau** [comment]
Or the other thing is not to keep old keys as that committed state (they were already "committed" once in the past) -- cleanup logic is "implicit" anyway; if the old keys are "implicit" as well (as they could be reconstructed by replaying the transactions), there's no need to change the nonce, put bounds on state size etc.

**Comment by yihuang** [comment]
> Or the other thing is not to keep old keys as that committed state (they were already "committed" once in the past) -- cleanup logic is "implicit" anyway; if the old keys are "implicit" as well (as they could be reconstructed by replaying the transactions), there's no need to change the nonce, put bounds on state size etc.

I don't understand.
I mean the cleanup logic what will set `staking.validator` to `None` after it become inactive for some time.
What do you mean by "not to keep old keys as that committed state"?

**Comment by tomtau** [comment]
`StakedState` is meant to represent the current account status and nonce in this context here is meant for making the state "current status" explicit by counting its updates; this is to prevent replay attacks. The commitment to that "current state" is through it being in the merkle trie.  

`used_validator_keys` do not really represent the "current status" (the current one is the key contained with `council_node`) -- all that information is already contained / was previously committed in the merkle trie.

->
- `used_validator_keys` can be implicit (as most of the logic with them) / moved out of there
- "clean state" can be just defined by that recorded time:
> * validator is none OR
> * Not jailed
> * block_time >= inactive_time + cleanup_period

i.e. once set, validator is never None

**Comment by yihuang** [comment]
From a practical point of view, either we change the nonce logic or provide a way for client to handle this situation would be ok. And it's not only related to clean up operation, but all the staking modify operations not initiated by tx broadcast by the user.
For example, if the client has a way to detect the failed tx execution due to incorrect nonce, it can safely update the nonce and retry.

**Comment by tomtau** [comment]
> For example, if the client has a way to detect the failed tx execution due to incorrect nonce, it can safely update the nonce and retry.

I think it should be possible e.g. with `block_results` RPC call -- as Tendermint includes both unsuccessful and successful TX in a block, one will see the unsuccessful TX in `deliver_tx`: it'll have  a non-zero code and "incorrect transaction count for account operation" in log

**Comment by tomtau** [comment]
(the error log message pre-dates begin block updates, hence it was called "transaction count")

**Comment by tomtau** [comment]
no relevant after https://github.com/crypto-com/chain-docs/pull/116/files
