### ISSUE TITLE
Problem:  Broken links to implementation plan in "Enclave Architecture"

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/thaler-docs#119]
All links to **implementation plan** only works in the markdown preview mode, but it wont work in https://crypto-com.github.io, see the [example](https://crypto-com.github.io/getting-started/enclave-architecture.html#enclave-infrastructure-overview) (by clicking the " implementation plan " link)

**Comment by lezzokafka** [comment]
The issue :`chain-docs/plan.md` is not included when running vuepress

**Comment by tomtau** [comment]
it was not meant to be included in the vuepress site -- one other things is the puml generation

**Comment by lezzokafka** [comment]
@tomtau Sure, I will point it to https://github.com/crypto-com/chain-docs/blob/master/plan.md then.
