### ISSUE TITLE
Problem: genesis page is not up to date

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler-docs#143]
1. genesis hash not documented
currently, only "genesis app hash" is documented.
But app hash is different from the overall genesis hash that's expected for light client verification

2. genesis page is outdated

**Comment by lezzokafka** [comment]
Besides describing what is this overall genesis hash, any suggestion on what should be inculded? @linfeng-crypto 
For example, how to obtain the genesis hash by `dev-utils genesis hash`?

**Comment by tomtau** [comment]
> Besides describing what is this overall genesis hash, any suggestion on what should be inculded? @linfeng-crypto
> For example, how to obtain the genesis hash by `dev-utils genesis hash`?

the important thing is to document its components and how it's calculated -- how to obtain isn't a big deal, as that command may change and for the testnet, it'll be provided in the documentation

**Comment by yihuang** [comment]
https://docs.tendermint.com/master/tendermint-core/light-client-protocol.html#where-to-obtain-trusted-height-hash

According to spec, light client seems should bootstrap from one trusted block rather than genesis.
But hash of genesis is more stable than hash of block 1 I guess.

**Comment by lezzokafka** [comment]
Will finish it once the renaming in [#1670](https://github.com/crypto-com/chain/issues/1670) is done.

**Comment by lezzokafka** [comment]
Can be closed by #145
