### ISSUE TITLE
Problem: nodejoin tx validation is not revised with TDBE-related changes (mls init + community node rules)

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler-docs#191]

**Comment by yihuang** [comment]
# TDBE node join validation

## abci state

```rust
enum TDBEState {
    Available,
    AwaitingCommit,
    PendingNACK,
}
struct TDBEVerifyState {
    epoch: u64,
    tree: TreePublicKey,
    state: TDBEState
}
```

## Verify `MLSInit` in `NodeJoinTx`

```rust
const cs: CipherSuite;
const ra_verifier: impl AttestedCertVerifier;
const group_id: Vec<u8>;

fn verify(state: &TDBEVerifyState, MLSInit::NodeJoin { add, commit }) {
    // verify state machine
    verify(state.state == TDBEState::Available)?;

    // verify epoch
    verify(state.epoch == commit.content.epoch)?;
  
    // verify message signature
    verify_signature(&tree, commit.sender, &commit)?;
    verify_signature(&tree, add.sender, &add)?;
  
    // verify keypackage in proposal
    add.key_package.verify()?;

    // update tree
    let updated_tree = update_tree(&self.tree, add);
  
    // compute transcript_hash
    let transcript_hash = compute_transcript_hash(
        cs, group_id, epoch, sender, commit
    );

    // construct group context
    let group_context = {
        epoch,
        updated_tree.compute_tree_hash(),
        transcript_hash,
    };

    // verify confirmation with TVE
    TVE.verify_confirmation(epoch, group_context, confirmation)?;
}
```

TVE will verify the confirmation like this:

```rust
fn TVE.verify_confirmation(epoch, group_context, confirmation) {
    // get init_secret and commit_secret from TDBE, either by push or pull.
    let (init_secret, commit_secret) = get_from_TDBE();
    let epoch_secrets = gen_epoch_secrets(init_secret, commit_secret, group_context);
    let confirmation_computed = epoch_secrets.compute_confirmation(group_context.transcript_hash);
    verify(confirmation_computed == confirmation)?;
}
```

After validation passed, increase the epoch, and set the tree to `updated_tree`.

```rust
state.epoch += 1;
state.tree = updated_tree;
```

**Comment by tomtau** [comment]
- should this also validate that the keypackage (or that there's no keypackage with the same identity and hpke pubkeys) isn't already in the tree?

- and for this "immediate update", should it also verify that path isn't filled in commit (it only needs to be filled for that "genesis-only" Add / Commit for the moment -- until there's a fix for issue 1 in https://mailarchive.ietf.org/arch/msg/mls/LtfodwWfdl36Y1FIbRAXHXDmCeU/ ), so that it doesn't need to worry about nack?

- instead of calculating confirmation for pre-calculated (from untrusted code) transcription hash, perhaps TVE could only be passed the new parts it couldn't know (updated_tree_hash or updated tree if it didn't maintain / get tree from tdbe, add, commit) and calculate group_context on its own

**Comment by yihuang** [comment]
> - instead of calculating confirmation for pre-calculated (from untrusted code) transcription hash, perhaps TVE could only be passed the new parts it couldn't know (updated_tree_hash or updated tree if it didn't maintain / get tree from tdbe, add, commit) and calculate group_context on its own

I think TVE should also cache the `GroupContext` and verify the passed one is the same, then compute and verify the confirmation.
