### ISSUE TITLE
getting started > compile enclave docs wrong

### ISSUE THREAD

**Issue by chatch** [crypto-com/thaler-docs#27]
Following the instructions here https://crypto-com.github.io/getting-started/#compile-enclave the compile fails (and it's pointing to an archived repo too) so I think it may be out of date?

**Comment by tomtau** [comment]
Yes, that's out of date -- the repo has been moved to the main repo: https://github.com/crypto-com/chain/tree/master/chain-tx-enclave

**Comment by lezzokafka** [comment]
@chatch  Hello there! 

Just a quick guide for building the enclave (Software version with [network id](https://crypto-com.github.io/getting-started/chain-id-and-network-id.html#chain-id-and-network-id ) = AB):

``` bash
git clone https://github.com/crypto-com/chain
cd chain
docker build -t chain-tx-validation \
-f ./chain-tx-enclave/tx-validation/Dockerfile . \
--build-arg SGX_MODE=SW \
--build-arg NETWORK_ID=AB
```

**Comment by tomtau** [comment]
I think this is now resolved with the latest getting started: https://crypto-com.github.io/getting-started/#build-binary-and-docker-images
