### ISSUE TITLE
Problem:  Tendermint need to be initiated before "Run chain components"

### ISSUE THREAD

**Issue by lezzokafka** [crypto-com/thaler-docs#57]
Tendermint has to be initiated before the step:   "[Run chain components](https://crypto-chain-doc.surge.sh/getting-started/#run-chain-components)",  
 if not, error message 
`ERROR: Failed to create node: Couldn't read GenesisDoc file: open /tendermint/config/genesis.json: no such file or directory`

Suggested solutions: 
- Easy one : add `make prepare` ( See the [make file](https://github.com/crypto-com/chain/blob/master/Makefile#L352) ) 
- Or just include make prepare in make run ?

**Comment by calvinlauyh** [comment]
I am claiming this task

**Comment by lezzokafka** [comment]
Closed by #129 

Thanks @calvinaco
