### ISSUE TITLE
Problem: missing link

### ISSUE THREAD

**Issue by landanhu** [crypto-com/thaler-docs#63]
Here https://crypto-com.github.io/getting-started/#congratulations mentions

> Congratulations, now the environment to run Crypto.com Chain is all set. Let's move on to start your first transaction.

I guess `start your first transaction` should be linked to https://crypto-com.github.io/getting-started/send_your_first_transaction.html#types-of-transaction-and-address?

**Comment by lezzokafka** [comment]
There will be quite a big change in #56, will keep an eye on this and fix it once it has been merged 👍🏻.
