### ISSUE TITLE
Problem: outdated and imprecise staking documentation

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler-docs#79]
Current docs: https://crypto-com.github.io/getting-started/staking.html

Some initial rough work: https://github.com/crypto-com/chain-docs/pull/75

Desired goals:

1. module-only specifics (e.g. reward calculation formulas) go into separate pages
2. cross-module interactions are explicitly stated
3. define precisely (somewhat "formally") in relation to Tendermint ABCI what each part does, so that this can be easily checked against the implementation:

- what are data inputs from where/when
- how are they processed
- what are outputs and when they are emitted

4. if the outcome depends on network parameters, each parameter needs to be justified:
- what it does
- what are its constraints
- what its relation to Tendermint core consensus security assumptions is -- "nothing-at-stake" problem, consensus-critical parameters set in Tendermint (evidence age, etc.), ...
- what it should be set to -- if it is not given (like total maximum supply), the recommended value should be given with justification / reference explaining why, e.g. based on mechanism design simulation models

**Comment by yihuang** [comment]
Add one thing, state the algorithm complexity.
