### ISSUE TITLE
Problem: reward<->punishment<->monetary update interactions not explicitly stated

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler-docs#81]
there should be a dedicated specification page

**Comment by tomtau** [comment]
"monetary update interactions" == transactions manipulating bonded amount (deposit_tx and unbond_tx)

**Comment by tomtau** [comment]
some early WIP: https://github.com/crypto-com/chain-docs/pull/75

**Comment by yihuang** [comment]
Also:
- How to choose active validators
- What's the status of validator who joined but not chosen into the top `max_validators`
- Liveness tracking of them
- Store validator metadata in an in-memory data structure or in the `StakedState` which is stored in a merkle trie. (I prefer the former, only let the merkle trie to handle the basic account model)

**Comment by yihuang** [comment]
We also need to clarify the nonce somewhere, which stats change should increase the nonce:
- bonded/unbonded change, definitely yes.
- council node metadata change?
- jail/unjail ?
- liveness tracker change, I guess no?

**Comment by tomtau** [comment]
> Also:
> 
> * How to choose active validators
> * What's the status of validator who joined but not chosen into the top `max_validators`
> * Liveness tracking of them
> * Store validator metadata in an in-memory data structure or in the `StakedState` which is stored in a merkle trie. (I prefer the former, only let the merkle trie to handle the basic account model)

yep, all of these are a part of this.
from the previous discussions / sketches:

 > How to choose active validators

non-punished, ordered by bonded amount, capped by max network parameter

> What's the status of validator who joined but not chosen into the top `max_validators`

reaching "max" isn't expected, so as always simplicity is preferred -- they'll just be removed without any punishments and need a manual action to rejoin (e.g. deposit more coins)... some of their data may need to be kept around for the unbonding period duration after they are gone

> Liveness tracking of them

more details needed in https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/punishments.md ?

> Store validator metadata in an in-memory data structure ...

it depends on what metadata -- one other consideration here is that this is potentially untrusted input, so if this metadata can grow by actions done by operators, it's a potential vector for DoS.
e.g. the pubkeys of byzantine actors don't need to be in merkle trie, but should be at least persisted in local kv-storage.

> We also need to clarify the nonce somewhere, which stats change should increase the nonce:
> 
> * council node metadata change?

yes
> * jail/unjail ?

yes
> * liveness tracker change, I guess no?

no

**Comment by yihuang** [comment]
> reaching "max" isn't expected, so as always simplicity is preferred -- they'll just be removed without any punishments and need a manual action to rejoin (e.g. deposit more coins)... some of their data may need to be kept around for the unbonding period duration after they are gone

Why don't we just sort out the logic once and for all, if max is not expected, why not simply remove the max parameter for now?

**Comment by yihuang** [comment]
> more details needed in https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/punishments.md ?

Yeah, it seems it doesn't say what happens to liveness tracker when validator get inactive, does it get cleanup immediately?
If it's cleaned up immediately, it seems there's a hole, say a validator is ranked at the edge of max validators with many non-participated blocks but not enough to get jailed, then he gets pushed out of validators because another validator join, the liveness tracker get cleaned up, then he deposit small amount of coins to become validator again, with a clean slate liveness tracking record. It's like resetting the liveness tracking record.
Maybe we should keep the track record for another tracking window after it becomes inactive.

**Comment by yihuang** [comment]
I think the nonce is only used to prevent replay attack on transaction broadcasted by the user, is there a need to increase it for internal or automatically events(like rewards, jail/unjail caused by internal events)?

**Comment by yihuang** [comment]
> it depends on what metadata -- one other consideration here is that this is potentially untrusted input, so if this metadata can grow by actions done by operators, it's a potential vector for DoS.
e.g. the pubkeys of byzantine actors don't need to be in merkle trie, but should be at least persisted in local kv-storage.

Yeah, I think it's safe to store all validator related stuff in an in-memory data structure, and serialized as a whole to persist in kv store, e.g. council node info, punishment bookkeeping, other index structures used for querying.
So in merkle trie, we only need: `bonded`, `unbonded`, `unbonded_from`, `nonce`? I think less stuff in merkle trie should simplify things a bit.

**Comment by tomtau** [comment]
Quite a lot of questions, better to post on Slack if these things weren't cleared out in @devashishdxt PR design

**Comment by devashishdxt** [comment]
@yihuang @tomtau What things do you think are still ambiguous in https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/punishments.md?

For liveness tracking,
> #### `EndBlock`
>
> - Update `LivenessTracker`, i.e., add all the validators who joined in current block and remove all the validator who, left/got jailed in current block.

That means, at the end of each block, we remove all the validators from liveness tracker who are no longer validators and add new validators. Isn't that clear enough? Do we need to change the language?

**Comment by devashishdxt** [comment]
> Yeah, it seems it doesn't say what happens to liveness tracker when validator get inactive, does it get cleanup immediately?
> If it's cleaned up immediately, it seems there's a hole, say a validator is ranked at the edge of max validators with many non-participated blocks but not enough to get jailed, then he gets pushed out of validators because another validator join, the liveness tracker get cleaned up, then he deposit small amount of coins to become validator again, with a clean slate liveness tracking record. It's like resetting the liveness tracking record.
> Maybe we should keep the track record for another tracking window after it becomes inactive.

The validator is cleaned up from `LivenessTracker` in `EndBlock` call and all the new validators added in that block are also added to `LivenessTracker` in `EndBlock`. And yes, if any the get moved out of the validator set and rejoin after depositing some extra amount, their `LivenessTracker` will be reset. Is there any problem you foresee because of resetting of `LivenessTracker`?

I'm not sure if keeping liveness history is a good idea because it increases complexity of the system (and we want to keep it simple).

**Comment by yihuang** [comment]
Actually, I'm not clear about what content should be put in this specification? what kind of precision it needs to be.

**Comment by tomtau** [comment]
> Actually, I'm not clear about what content should be put in this specification? what kind of precision it needs to be.

it can be iterative -- the sort of precision that's in current reward/punishment docs is likely all right (English descriptions, code snippets of core data types or pseudocode). Examples of important parts:
- invariants -- what each part expects to hold at all times or at specific times
- (implications for the implementation -- what to watch out for)
- multiple ops on the same account (in BeginBlock or DeliverTx) -- clarification on how they should happen
- endblock output in terms of ValidatorUpdates that can be turned into high-level unit tests or quickcheck properties 
...

The target audience would be a person to implement it or to review the initial implementation against.
And anyone in the future who tries to change the implementation (or code review PR changing the implementation) and check against the doc for clarity over whether the things mentioned there still hold.
